version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: dr_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ml_service:
    build: ./ml_service
    container_name: dr_ml
    ports:
      - "8000:8000"

  backend:
    build: ./server
    container_name: dr_backend
    ports:
      - "9000:9000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
      - ml_service

  client:
    build: ./client
    container_name: dr_client
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
